Name: SensityPVPCore
api: 3.0.0
main: CV71\Anni\Annihilation
Author: CV71
Version: 1.8.0

Commands:
         help:
         description:"shows a list of commands"
         setup:
         description:"SetUp mode For Anni"
         green:
         description:"select Green Anni Team"
         yellow
         description:"select Yellow Anni Team"
         blue:
         description:"select Blue Anni Team"
         red:
         description:"select Red Anni Team"
         class:
         description:"select your kit"


